# Generated by Django 2.2.26 on 2022-03-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UKCB', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='Text',
        ),
    ]
