# Generated by Django 2.2.26 on 2022-03-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UKCB', '0002_auto_20220309_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
